### ISSUE TITLE
Add function to create automaton accepting single word

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#166]
In the near future, we will need a function which will create a simple automaton accepting a single word passed as an argument.

The function should look like the following:
```cpp
/**
 * Create automaton accepting only a single word @p word.
 */
Nfa create_single_word_nfa(const std::string& word);
```

However, we need to decide on how to obtain symbols from the word for transitions in the automaton. Should the word be a string, vector of strings (each element one symbol name) or something different? What should be the internal symbol values? 

We will need to discuss this further.

**Comment by Adda0** [comment]
@vhavlena Do you have any specific requirements on what should the word be? How should the word be represented? We might want to pass an alphabet as a parameter, too. If you could answer the questions in this issue from your point of view, it would help immensely.

**Comment by vhavlena** [comment]
From the z3 point of view, it suffices to represent word as a sequence of numbers (because in z3 we do not have this correspondence between symbols and numbers, we have just numbers). From a library point of view, it makes sense to the word be specified by a sequence of symbols and the method translates the symbols according to the given alphabet.
