### ISSUE TITLE
Add guide on how to work with and maintain Python binding

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#242]
We should create a document explaining how to work with and maintain Python binding in case all our Python binding developers (both of them!) are met with an unfortunate accident.

The document should explain how to maintain the binding, extend the binding further, and where to look when something breaks and someone needs to fix the errors.

**Comment by tfiedor** [comment]
Is this and #241 necessary to have as separate issues? I think it could be included in #229 as subissues/steps.

**Comment by Adda0** [comment]
Those are two unrelated issues as far as I am concerned. One is strictly about implementation which does not affect the guide at all, the other is about documentation in a separate text file. What I find most important is that either can be resolved without having to close the other one. I do not expect to resolve both issues in a single PR. That would be a massive PR. I would rather see one PR for updating Python binding, other for creating the above-mentioned document. What do you think about this?

**Comment by tfiedor** [comment]
I see your point, I just think that 3 issues might be too much :). IMO it could be merge into one, or at least have one for bringing binding up to date, including refactoring some of the code (e.g. breaking into modules) and one for documentation.

My point is, that we have too many issues :-D 

EDIT: Also, I have created a task in my Notion setup already for the binding, and I'm quite reluctant to update it now :D

**Comment by Adda0** [comment]
> My point is, that we have too many issues :-D

Personally, I disagree. The problem is that we do not have enough man-power to resolve all the issues immediately. The issue either makes sense or it does not. Whether it is the 101st or 3rd issue does not mean anything.

> EDIT: Also, I have created a task in my Notion setup already for the binding, and I'm quite reluctant to update it now :D

This is a valid argument in my point of view. We would not want to force you to redo that, now, would we?

If we are confident that all of these Python binding-related issues will be resolved in a single PR, we can merge these issues. Alternatively, we can tick each checkbox in the merged issue with each PR. But then we are imitating the behaviour of having separate issues again. This is purely a matter of taste and habit, I believe.

Therefore, I will merge these issues into a single issue #229 with tasks inside. When we merge a PR, we will tick the checkbox for the resolved issues one at a time.

**Comment by tfiedor** [comment]
Ook. I mean we can have multiple PR for single issue. That might be suitable compromise. I agree that your proposal Is better, but because we have over 40 issues it might be easier to merge them  to single issue with checklist to declutter the Space Dne 2. 6. 2023 13:02 napsal uživatel David Chocholatý ***@***.***>:

My point is, that we have too many issues :-D

Personally, I disagree. The problem is that we do not have enough man-power to resolve all the issues immediately. The issue either makes sense or it does not. Whether it is the 101st or 3rd issue does not mean anything.

EDIT: Also, I have created a task in my Notion setup already for the binding, and I'm quite reluctant to update it now :D

This is a valid argument in my point of view. We would not want to force you to redo that, now, would we?
If we are confident that all of these Python binding-related issues will be resolved in a single PR, we can merge these issues. Alternatively, we can tick each checkbox in the merged issue with each PR. But then we are imitating the behaviour of having separate issues again. This is purely a matter of taste and habit, I believe.
Therefore, I will merge these issues into a single issue #229 with tasks inside. When we merge a PR, we will tick the checkbox for the resolved issues one at a time.
