### ISSUE TITLE
Lazy evaluation of operations to get some accepted word

### ISSUE THREAD

**Issue by jurajsic** [VeriFIT/mata#415]
For Z3-Noodler, I need to get a word from application of operations on automata while **not** constructing the resulting automaton (as it can blow-up).
More specifically I need:
- [x] a word from a complement of an NFA, without computing the whole complement
- [x] having two NFAs A1 and A2, I need a word from L(A1) ∩ L(A2)', where again, the complement is the problem

The first problem could be solved by doing determinization and stopping when some macrostate does not contain any final state. The second is harder, I do not know how to do it.

**Comment by vhavlena** [comment]
The second one is language difference, no? It should be similar to the first case, the only difference is that a macrostate looks like `(q,S)` not just `S`.

**Comment by jurajsic** [comment]
Yes, it's language difference. And yes, the macrostate would be `(q,S)`, but I think implementation-wise it will be harder (for the first case, we can just reuse the determinization implementation).

**Comment by Adda0** [comment]
For the implementation of `get_word_from_complement(Nfa nfa_to_complement)`, we could modify the existing determinization algorithm. We could add an optional callback function, similarly to how we handle callback functions in Tarjan's algorithm, for example, where the callback would be an event handler for encountering a new macrostate. If the callback is defined and returns `true`, the determinization continues, otherwise the determinization stops. In this case, the callback would check the final states in the macrostate and return `false` if there is none (the macrostate is a final state in the complement). The determinization then returns the DFA created so far.

For the language difference, this callback could be maybe utilized, too. However, you would have to take into account the transition symbols leading to this macrostate. Or possibly the outgoing transition symbols.

Does this sound reasonable?

**Comment by vhavlena** [comment]
It could work. It is quite useful to add the language difference operation and then this kind of callback extension should be easy.

**Comment by Adda0** [comment]
I have implemented `nfa::Nfa::get_word_from_complement()`. The PR will be created once the PRs the implementation depends on get merged.

**Comment by Adda0** [comment]
I am working on implementing `nfa::get_word_from_lang_difference()`. I will hopefully finish the implementation today and create a PR with implementation for lazy computation of language difference and lazily getting an arbitrary word from the result. This PR will close this issue.

**Comment by jurajsic** [comment]
That's great! It's ok if it is not done today, or even this week, I still haven't got to using all the other stuff you already implemented last two weeks :D

**Comment by Adda0** [comment]
I want to finish this, so I can get to working on replace all operations and rebasing the implementation of transducers onto the current `devel` with all the breaking changes at once. I do not want to prolong the inevitable rebase of the branch with transducers onto the `devel` branch.
