### ISSUE TITLE
Add support for epsilon

### ISSUE THREAD

**Issue by martinhruska** [VeriFIT/mata#56]
We agreeed that it would be nice to add to alphabets support for defining epsilon.

**Comment by Adda0** [comment]
We have decided that, for now, there should be only one epsilon symbol: a constant with the value of the maximal value of `unsigned long` (our current `Symbol` type) and for efficient access to epsilon transitions symbol in `TransitionList`, we will need to add `back()` access function to `OrdVector` (reimplementation of `std::vector<T>::back()`). Therefore, the alphabet does not know anything about the epsilon symbol. Epsilon symbols are independent of the definition of alphabets.

If there are requirements for multiple epsilon symbols in the future, an additional interface allowing the specification of multiple epsilon symbols will be added. Specifically, alphabets will have to allow specification of a sequence of symbol to be treated as epsilon symbols.

In the case of NFAs with defined alphabets with multiple epsilon symbols, we have two options: treat the default constant alphabet-independent epsilon symbol (which is not specified inside the alphabet) as:
1. a normal symbol instead of an epsilon symbol, or
2. an epsilon symbol.

I prefer the option 1. This seems more intuitive to me and simplifies the algorithms working with epsilon symbols by not having to test each time whether the current symbol is in the sequence of user-specified epsilon symbols and whether it is the constant epsilon symbol.

This also directly affects the implementation of #55.

**Comment by martinhruska** [comment]
Ok, I'm gonna proceed with option 2).

**Comment by Adda0** [comment]
Option 2 is fine with me, too. Proceed.

**Comment by martinhruska** [comment]
Implemented in PR #68

**Comment by martinhruska** [comment]
Solved by PR #68
