### ISSUE TITLE
Add proper tests for regex parser

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#60]
We need to add more tests for parser of regexes. Test the parser on more complex regexes and confirm that the parser gives correct automata.

Furthermore, it would be useful to add tests for the whole pipeline from smtlib to NFA.

We might be able to take inspiration from [tests for RE2](https://github.com/google/re2/tree/main/re2/testing).

**Comment by martinhruska** [comment]
What is state of this issue?

**Comment by martinhruska** [comment]
@Adda0 @vhavlena ?

**Comment by Adda0** [comment]
There are some tests. The parser seems to be working as of now. Nevertheless, there could be more tests covering additional aspects of automata parsing not yet covered by any test. The current test suite is neither through nor systematic. Instead, the current test suite have been done ad-hoc for at the time required features.

**Comment by vhavlena** [comment]
We have a couple of tests now. Definitely more than at the time of creating this issue. The problem is that the regex->NFA construction is heavily used in the string solving. Maybe we could employ some kind of fuzz testing to make it more convincing. For instance we could randomly generate RE2 regexes together with strings and compare the membership test with the result of some pattern matcher (grep or whatever).
